package sequencer

import (
	"context"

	"github.com/sig-0/go-ibft/message"
)

func (s *Sequencer) sendMsgCommit() {
	msg := &message.Commit{
		Sequence:   s.sequence.sequence,
		Round:      s.sequence.round,
		Sender:     s.validator.Address(),
		BlockHash:  s.sequence.acceptedBlockHash(),
		CommitSeal: s.validator.Sign(s.sequence.acceptedBlockHash()),
	}

	msg.Signature = s.validator.Sign(msg.Payload())

	s.transport.MulticastCommit(msg)
}

func (s *Sequencer) awaitCommitQuorum(ctx context.Context) ([]*message.Commit, error) {
	sub, cancelSub := s.feed.CommitMessages.Subscribe(s.sequence.sequence, s.sequence.round, false)
	defer cancelSub()

	//cache := message.NewCache(s.isValidMsgCommit)

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case notification := <-sub:
			//cache.Add(notification()...)

			messages, err := s.vrf.CheckCommit(ctx, &s.sequence, notification())
			if err != nil {
				// todo: log
				continue
			}

			return messages, nil

			//commits := cache.Get()
			//addresses := make([][]byte, 0, len(commits))
			//for _, commit := range commits {
			//	addresses = append(addresses, commit.GetSender())
			//}
			//
			//if len(commits) == 0 || !s.verifier.HasQuorum(addresses, s.state.sequence) {
			//	continue
			//}
			//
			//return commits, nil
		}
	}
}

//
//func (s *Sequencer) isValidMsgCommit(msg *message.Commit) bool {
//	// sender must be part of the validator set
//	if !s.verifier.IsValidator(msg.Sender, msg.Sequence) {
//		return false
//	}
//
//	// block hash and accepted block hash must match
//	if !bytes.Equal(msg.BlockHash, s.state.acceptedBlockHash()) {
//		return false
//	}
//
//	// commit seal was generated by signing block hash
//	if err := s.verifier.IsValidSignature(msg.Sender, msg.BlockHash, msg.CommitSeal); err != nil {
//		return false
//	}
//
//	return true
//}
