syntax = "proto3";

package message;

option go_package = "github.com/sig-0/go-ibft/message;message";

// MsgProposal is the initial consensus message that starts the finalization process. It's gossiped by
// a chosen proposer in a specific round and represents the proposal being voted on by the network
message Proposal {
  // Sequence in which the message was created
  uint64 sequence = 1;

  // Round in which the message was created
  uint64 round = 2;

  // ID of the validator who sent the message
  bytes sender = 3;

  // Validator's signature over the message
  bytes signature = 4;

  // Proposal being voted on
  ProposedBlock proposed_block = 5;

  // Keccak hash of the proposed_block
  bytes block_hash = 6;

  // Proof that a round-change occurred in the previous round
  RoundChangeCertificate round_change_certificate = 7;
}

// MsgPrepare is sent when a validator accepts a proposal
message Prepare {
  // Sequence in which the message was created
  uint64 sequence = 1;

  // Round in which the message was created
  uint64 round = 2;

  // ID of the validator who sent the message
  bytes sender = 3;

  // Validator's signature over the message
  bytes signature = 4;

  // Keccak hash of the proposal being voted on
  bytes block_hash = 5;
}

// MsgCommit is a validator's commitment on a proposal that passed the PREPARE phase
message Commit {
  // Sequence in which the message was created
  uint64 sequence = 1;

  // Round in which the message was created
  uint64 round = 2;

  // ID of the validator who sent the message
  bytes sender = 3;

  // Validator's signature over the message
  bytes signature = 4;

  // Keccak hash of the proposal being voted on
  bytes block_hash = 5;

  // Validator's signature over block_hash
  bytes commit_seal = 6;
}

// MsgRoundChange is sent when a validator's round timer expires
message RoundChange {
  // Sequence in which the message was created
  uint64 sequence = 1;

  // Round in which the message was created
  uint64 round = 2;

  // ID of the validator who sent the message
  bytes sender = 3;

  // Validator's signature over the message
  bytes signature = 4;

  // Proposal from previous round
  ProposedBlock latest_prepared_proposed_block = 5;

  // Certificate proving network accepted the ProposedBlock but did not commit
  PreparedCertificate latest_prepared_certificate = 6;
}

// ProposedBlock is the proposer's block
message ProposedBlock {
  // Proposed block content
  bytes block = 1;

  // Round in which the block was proposed
  uint64 round = 2;
}

// PreparedCertificate is the last proposal to pass the PREPARE phase
message PreparedCertificate {
  // The original MsgProposal
  Proposal proposal_message = 1;

  // Proof the original message passed PREPARE phase
  repeated Prepare prepare_messages = 2;
}

// RoundChangeCertificate is a collection of round-change messages used as proof that validators moved to a new round
message RoundChangeCertificate {
  repeated RoundChange messages = 1;
}


