package consensus

import (
	"bytes"
	"context"

	"github.com/sig-0/go-ibft/message"
	"github.com/sig-0/go-ibft/sequencer"
)

func (c Consensus) AwaitCommit(ctx context.Context, seq sequencer.Sequence, store *message.Store) ([]*message.Commit, error) {
	seen := make(map[string]struct{})
	valid := make([]*message.Commit, 0)
	sequence := seq.Number
	round := seq.Round

	sub, cancel := store.CommitMessages.Subscribe(sequence)
	defer cancel()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case unwrap := <-sub:
			messages := unwrap()
			for _, msg := range messages {
				if _, ok := seen[string(msg.Signature)]; ok {
					continue
				}

				seen[string(msg.Signature)] = struct{}{}

				if msg.Round != round {
					// only interested in active round
					continue
				}

				if !c.isValidCommit(ctx, seq, msg) {
					continue
				}

				valid = append(valid, msg)
			}
		}

		getValidators := func(messages ...*message.Commit) [][]byte {
			validators := make([][]byte, 0, len(messages))
			for _, msg := range messages {
				validators = append(validators, msg.Signature)
			}

			return validators
		}

		ok, err := c.vs.CheckQuorum(ctx, sequence, getValidators(valid...))
		if err != nil {
			// todo: log
			continue
		}

		if !ok {
			continue
		}

		return valid, nil
	}
}

func (c Consensus) isValidCommit(ctx context.Context, seq sequencer.Sequence, msg *message.Commit) bool {
	// sender must be part of the validator set
	if _, ok := c.currentValidators[string(msg.Sender)]; !ok {
		return false
	}

	// block hash and accepted block hash must match
	if !bytes.Equal(msg.BlockHash, seq.Proposal.BlockHash) {
		return false
	}

	// commit seal was generated by signing block hash
	if err := c.sig.Verify(msg.Sender, msg.BlockHash, msg.CommitSeal); err != nil {
		return false
	}

	return true
}
