package consensus

import (
	"bytes"
	"context"

	"github.com/sig-0/go-ibft/message"
	"github.com/sig-0/go-ibft/sequencer"
)

func (c Consensus) AwaitCommit(
	ctx context.Context,
	seq sequencer.Sequence,
	store *message.Store,
) ([]*message.Commit, error) {
	var (
		sequence = seq.Number
		round    = seq.Round
		seen     = make(map[string]struct{})
		valid    = make([]*message.Commit, 0)
	)

	sub, cancel := store.CommitMessages.Subscribe(sequence)
	defer cancel()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case unwrap := <-sub:
			messages := unwrap()
			candidates := make([]*message.Commit, 0, len(messages))
			for _, msg := range messages {
				if msg.Round != round {
					continue
				}

				if _, ok := seen[string(msg.Signature)]; ok {
					continue
				}

				seen[string(msg.Signature)] = struct{}{}

				candidates = append(candidates, msg)
			}

			valid = filterValidCommitMessages(ctx, c, candidates, seq)

			getValidators := func(messages ...*message.Commit) [][]byte {
				validators := make([][]byte, 0, len(messages))
				for _, msg := range messages {
					validators = append(validators, msg.Sender)
				}

				return validators
			}

			ok, err := c.vs.CheckQuorum(ctx, sequence, getValidators(valid...))
			if err != nil || !ok {
				continue
			}

			return valid, nil
		}
	}
}

func (c Consensus) isValidCommit(ctx context.Context, seq sequencer.Sequence, msg *message.Commit) bool {
	// sender must be part of the validator set
	if _, ok := c.currentValidators[string(msg.Sender)]; !ok {
		return false
	}

	// block hash and accepted block hash must match
	if !bytes.Equal(msg.BlockHash, seq.Proposal.BlockHash) {
		return false
	}

	// commit seal was generated by signing block hash
	if err := c.sig.Verify(msg.Sender, msg.BlockHash, msg.CommitSeal); err != nil {
		return false
	}

	return true
}
