package consensus

import (
	"context"

	"github.com/sig-0/go-ibft/message"
	"github.com/sig-0/go-ibft/sequencer"
)

type Consensus struct {
}

func (c Consensus) AwaitProposal(ctx context.Context, sequence sequencer.Sequence, store *message.Store, fromHigherRounds bool) (*message.Proposal, error) {
	//TODO implement me
	panic("implement me")
}

func (c Consensus) AwaitRoundChange(ctx context.Context, sequence sequencer.Sequence, store *message.Store, fromHigherRounds bool) ([]*message.RoundChange, error) {
	//TODO implement me
	panic("implement me")
}

func (c Consensus) AwaitPrepare(ctx context.Context, sequence sequencer.Sequence, store *message.Store) ([]*message.Prepare, error) {
	//TODO implement me
	panic("implement me")
}

func (c Consensus) AwaitCommit(ctx context.Context, sequence sequencer.Sequence, store *message.Store) ([]*message.Commit, error) {
	//TODO implement me
	panic("implement me")
}

//
//func (s *Sequencer) awaitCommit(
//	ctx context.Context,
//	sequence *Sequence,
//	messages *message.Store,
//) ([]*message.Commit, error) {
//	sub, cancelSub := messages.CommitMessages.Subscribe(sequence.sequence, sequence.round, false)
//	defer cancelSub()
//
//	//cache := message.NewCache(s.isValidMsgCommit)
//
//	for {
//		select {
//		case <-ctx.Done():
//			return nil, ctx.Err()
//		case notification := <-sub:
//			//cache.Add(notification()...)
//
//			messages, err := s.consensus.go.AwaitCommit(ctx, *sequence, notification())
//			if err != nil {
//				// todo: log
//				continue
//			}
//
//			return messages, nil
//
//			//commits := cache.Get()
//			//addresses := make([][]byte, 0, len(commits))
//			//for _, commit := range commits {
//			//	addresses = append(addresses, commit.GetSender())
//			//}
//			//
//			//if len(commits) == 0 || !s.verifier.HasQuorum(addresses, s.state.sequence) {
//			//	continue
//			//}
//			//
//			//return commits, nil
//		}
//	}
//}

//
//func (s *Sequencer) isValidMsgCommit(msg *message.Commit) bool {
//	// sender must be part of the validator set
//	if !s.verifier.IsValidator(msg.Sender, msg.Sequence) {
//		return false
//	}
//
//	// block hash and accepted block hash must match
//	if !bytes.Equal(msg.BlockHash, s.state.acceptedBlockHash()) {
//		return false
//	}
//
//	// commit seal was generated by signing block hash
//	if err := s.verifier.IsValidSignature(msg.Sender, msg.BlockHash, msg.CommitSeal); err != nil {
//		return false
//	}
//
//	return true
//}

//
//func (s *Sequencer) awaitPrepare(
//	ctx context.Context,
//	sequence *Sequence,
//	store *message.Store,
//) ([]*message.Prepare, error) {
//	sub, cancelSub := store.PrepareMessages.Subscribe(sequence.sequence, sequence.round, false)
//	defer cancelSub()
//
//	//cache := message.NewCache(s.isValidMsgPrepare)
//
//	for {
//		select {
//		case <-ctx.Done():
//			return nil, ctx.Err()
//		case notification := <-sub:
//			//cache.Add(notification()...)
//
//			messages, err := s.consensus.go.AwaitPrepare(ctx, *sequence, notification())
//			if err != nil {
//				// todo: log
//				continue
//			}
//
//			return messages, nil
//
//			//prepares := cache.Get()
//			//addresses := make([][]byte, 0, len(prepares))
//			//for _, commit := range prepares {
//			//	addresses = append(addresses, commit.GetSender())
//			//}
//			//
//			//if !s.verifier.HasQuorum(addresses, s.state.sequence) {
//			//	continue
//			//}
//			//
//			//return prepares, nil
//		}
//	}
//}

//
//func (s *Sequencer) isValidMsgPrepare(msg *message.Prepare) bool {
//	// sender is part of the validator set
//	if !s.verifier.IsValidator(msg.Sender, msg.Sequence) {
//		return false
//	}
//
//	// block hash and accepted block hash match
//	if !bytes.Equal(msg.BlockHash, s.state.acceptedBlockHash()) {
//		return false
//	}
//
//	return true
//}

//
//func (s *Sequencer) awaitProposal(
//	ctx context.Context,
//	sequence *Sequence,
//	store *message.Store,
//	higherRounds bool,
//) (*message.Proposal, error) {
//	round := sequence.round
//	if higherRounds {
//		round++
//	}
//
//	sub, cancelSub := store.ProposalMessages.Subscribe(sequence.sequence, round, higherRounds)
//	defer cancelSub()
//
//	//cache := message.NewCache(s.isValidMsgProposal)
//
//	for {
//		select {
//		case <-ctx.Done():
//			return nil, ctx.Err()
//		case notification := <-sub:
//			//cache.Add(notification()...)
//			msg, err := s.vrf.CheckProposal(ctx, *sequence, notification())
//			if err != nil {
//				// todo: log
//				continue
//			}
//
//			return msg, nil
//
//			//proposals := cache.Get()
//			//if len(proposals) == 0 {
//			//	continue
//			//}
//			//
//			//return proposals[0], nil
//		}
//	}
//}

//
//func (s *Sequencer) isValidMsgProposal(msg *message.Proposal) bool {
//	// msg round and proposed block round match
//	if msg.ProposedBlock.Round != msg.Round {
//		return false
//	}
//
//	// sender is part of the validator set
//	if bytes.Equal(msg.Sender, s.validator.Address()) {
//		return false
//	}
//
//	// sender is the selected proposer
//	if !s.verifier.IsProposer(msg.Sender, msg.Sequence, msg.Round) {
//		return false
//	}
//
//	// block hash and keccak hash of proposed block match
//	if !bytes.Equal(msg.BlockHash, s.keccak(msg.ProposedBlock.Bytes())) {
//		return false
//	}
//
//	if msg.Round == 0 {
//		return s.verifier.IsValidProposal(msg.ProposedBlock.Block, msg.Sequence)
//	}
//
//	/* non zero round proposals */
//
//	rcc := msg.RoundChangeCertificate
//	if !s.isValidRCC(rcc, msg) {
//		return false
//	}
//
//	trimmedRCC := &message.RoundChangeCertificate{}
//	for _, msg := range rcc.Messages {
//		pc := msg.LatestPreparedCertificate
//		if pc == nil {
//			continue
//		}
//
//		// any included prepared certificate must be valid
//		if s.isValidPC(pc, msg) {
//			trimmedRCC.Messages = append(trimmedRCC.Messages, msg)
//		}
//	}
//
//	blockHash, round := trimmedRCC.HighestRoundBlockHash()
//	if blockHash == nil {
//		// there is no previously agreed upon block hash, build a new proposal
//		return s.verifier.IsValidProposal(msg.ProposedBlock.Block, msg.Sequence)
//	}
//
//	// reuse the proposed block from previous (highest) round
//	pb := &message.ProposedBlock{
//		Block: msg.ProposedBlock.Block,
//		Round: round,
//	}
//
//	// block hash and a keccak hash of proposed block match
//	return bytes.Equal(blockHash, s.keccak(pb.Bytes()))
//}

//
//func (s *Sequencer) awaitRCC(
//	ctx context.Context,
//	sequence *Sequence,
//	higherRounds bool,
//	store *message.Store,
//) (*message.RoundChangeCertificate, error) {
//	round := sequence.round
//	if higherRounds {
//		round++
//	}
//
//	sub, cancelSub := store.RoundChangeMessages.Subscribe(sequence.sequence, round, higherRounds)
//	defer cancelSub()
//
//	//cache := message.NewCache(s.isValidMsgRoundChange)
//
//	for {
//		select {
//		case <-ctx.Done():
//			return nil, ctx.Err()
//		case notification := <-sub:
//			//cache.Add(notification()...)
//
//			messages, err := s.consensus.go.AwaitRoundChange(ctx, *sequence, notification(), false)
//			if err != nil {
//				continue
//				// todo: log
//			}
//
//			//roundChanges := cache.Get()
//			//addresses := make([][]byte, 0, len(roundChanges))
//			//for _, commit := range roundChanges {
//			//	addresses = append(addresses, commit.GetSender())
//			//}
//			//
//			//if len(roundChanges) == 0 || !s.verifier.HasQuorum(addresses, s.state.sequence) {
//			//	continue
//			//}
//
//			return &message.RoundChangeCertificate{Messages: messages}, nil
//
//		}
//	}
//}

//
//func (s *Sequencer) isValidMsgRoundChange(msg *message.RoundChange) bool {
//	// sender is part of the validator set
//	if !s.verifier.IsValidator(msg.Sender, msg.Sequence) {
//		return false
//	}
//
//	var (
//		pb = msg.LatestPreparedProposedBlock
//		pc = msg.LatestPreparedCertificate
//	)
//
//	// if both pb and pc are missing, the message is valid
//	if pb == nil && pc == nil {
//		return true
//	}
//
//	// both pb and pc must be set
//	if pb == nil || pc == nil {
//		return false
//	}
//
//	if !s.isValidPC(pc, msg) {
//		return false
//	}
//
//	// block hash in proposal message and keccak hash of proposed block match
//	if !bytes.Equal(pc.ProposalMessage.BlockHash, s.keccak(pb.Bytes())) {
//		return false
//	}
//
//	return true
//}
//
//func (s *Sequencer) isValidPC(pc *message.PreparedCertificate, msg *message.RoundChange) bool {
//	// both proposal message and prepare messages must be included
//	if pc.ProposalMessage == nil || pc.PrepareMessages == nil {
//		return false
//	}
//
//	var (
//		sequence = pc.ProposalMessage.Sequence
//		round    = pc.ProposalMessage.Round
//	)
//
//	// proposal sequence in pc and msg sequence must match
//	if sequence != msg.Sequence {
//		return false
//	}
//
//	// proposal round in pc must be higher than the round of the msg
//	if round >= msg.Round {
//		return false
//	}
//
//	// proposal sender in pc must be the selected proposer
//	if !s.verifier.IsProposer(pc.ProposalMessage.Sender, sequence, round) {
//		return false
//	}
//
//	uniqueSenders := map[string]struct{}{
//		string(pc.ProposalMessage.Sender): {}, // proposer
//	}
//
//	for _, msg := range pc.PrepareMessages {
//		// prepare msg sequence (round) and proposal msg sequence (round) must match
//		if msg.Sequence != sequence || msg.Round != round {
//			return false
//		}
//
//		// prepare msg block hash and proposal msg block hash must match
//		if !bytes.Equal(msg.BlockHash, pc.ProposalMessage.BlockHash) {
//			return false
//		}
//
//		// prepare msg sender must be part of the validator set
//		if !s.verifier.IsValidator(msg.Sender, sequence) {
//			return false
//		}
//
//		uniqueSenders[string(msg.Sender)] = struct{}{}
//	}
//
//	// 1 (proposer) + len(prepare) unique validators
//	if len(uniqueSenders) != 1+len(pc.PrepareMessages) {
//		return false
//	}
//
//	senders := make([][]byte, len(uniqueSenders))
//	for sender, _ := range uniqueSenders {
//		senders = append(senders, []byte(sender))
//	}
//
//	// all messages in pc satisfy a quorum
//	if !s.verifier.HasQuorum(senders, sequence) {
//		return false
//	}
//
//	return true
//}
//
//func (s *Sequencer) isValidRCC(rcc *message.RoundChangeCertificate, proposal *message.Proposal) bool {
//	// rcc must be included
//	if rcc == nil || len(rcc.Messages) == 0 {
//		return false
//	}
//
//	var (
//		sequence      = proposal.Sequence
//		round         = proposal.Round
//		uniqueSenders = make(map[string]struct{})
//	)
//
//	for _, msg := range rcc.Messages {
//		// round change msg sequence (round) and proposal msg sequence (round) must match
//		if msg.Sequence != sequence || msg.Round != round {
//			return false
//		}
//
//		// sender must be part of the validator set
//		if !s.verifier.IsValidator(msg.Sender, sequence) {
//			return false
//		}
//
//		uniqueSenders[string(msg.Sender)] = struct{}{}
//	}
//
//	// all messages must be unique
//	if len(uniqueSenders) != len(rcc.Messages) {
//		return false
//	}
//
//	senders := make([][]byte, len(uniqueSenders))
//	for sender, _ := range uniqueSenders {
//		senders = append(senders, []byte(sender))
//	}
//
//	// all messages in rcc satisfy a quorum
//	if !s.verifier.HasQuorum(senders, sequence) {
//		return false
//	}
//
//	return true
//}
